/** Labels in Spanish for the SOC dashboard. Import as: import { L } from "@/lib/soc-labels" */

export const L = {
  header: {
    title: "Consola IDS OT/IT",
    env: "SOC Staging",
    updated: "Actualizado",
    storage: "Almacenamiento",
  },
  kpi: {
    totalEvents: "Total eventos",
    critical: "Críticos",
    high: "Altos",
    medium: "Medios",
    otEvents: "Eventos OT",
    itEvents: "Eventos IT",
    highCritical: "Altos/Críticos",
    services: "Servicios",
    riskScore: "Puntuación de riesgo",
  },
  panels: {
    attackMap: "Mapa táctico de ataques",
    topology: "Topología OT/IT",
    timeline: "Línea temporal",
    threatRadar: "Radar de amenazas",
    assets: "Inteligencia de activos",
    ioCs: "Indicadores de amenaza",
    recentEvents: "Eventos recientes",
    investigation: "Investigación del evento",
    severityDistribution: "Distribución de severidad",
  },
  events: {
    selectEvent: "Selecciona un evento para iniciar investigación",
    noEvents: "Sin eventos recientes",
    time: "Hora",
    severity: "Severidad",
    type: "Tipo",
    protocol: "Protocolo",
    source: "Origen",
    destination: "Destino",
    zone: "Zona",
    titleCol: "Título",
    id: "ID",
    direction: "Dirección",
    tags: "Etiquetas",
  },
  scoring: {
    scoreEvent: "Score seleccionado",
    scoring: "Analizando...",
    factors: "Factores",
    recommendations: "Recomendaciones",
  },
  threat: {
    scan: "Escaneo",
    auth: "Autenticación",
    proto: "Protocolo",
    malware: "Malware",
    lateral: "Lateral",
    external: "Externo",
  },
  assets: {
    noAssets: "Sin activos detectados",
    ip: "IP",
    events: "Eventos",
    critHigh: "Crít/Altos",
    criticality: "Criticidad",
    protocols: "Protocolos",
    lastSeen: "Última vez",
  },
  ioCs: {
    noIoCs: "Sin IoCs detectados",
    sourceIp: "IP origen",
    threatType: "Tipo amenaza",
    count: "Cantidad",
    targets: "Destinos",
  },
  topology: {
    nodes: "nodos",
    edges: "enlaces",
  },
  timeline: {
    buckets: "bloques",
    perMin: "1 min",
  },
  severity: {
    critical: "Crítico",
    high: "Alto",
    medium: "Medio",
    low: "Bajo",
    info: "Info",
  },
  zones: {
    external: "🌐 Externo",
    dmz: "🛡 DMZ",
    it: "💻 IT",
    ot: "⚙ OT",
    unknown: "❓",
  },
  services: {
    core: "ids-core",
    analytics: "analytics-api",
    mcp: "mcp-server",
    web: "ids-web",
  },
};
